"""empty message

Revision ID: 131d9cf66924
Revises: 
Create Date: 2025-05-22 16:01:51.350244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131d9cf66924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visible_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('product', 'category', 'sous_category', 'boutique', 'article', 'application', name='itemtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visible_items')
    # ### end Alembic commands ###
