"""Add Historique table

Revision ID: 89c692c24d3f
Revises: d843015a7a68
Create Date: 2025-06-11 14:51:05.946962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c692c24d3f'
down_revision = 'd843015a7a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historiques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('produit', sa.String(length=100), nullable=False),
    sa.Column('duree', sa.String(length=50), nullable=False),
    sa.Column('codes', sa.Text(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historiques')
    # ### end Alembic commands ###
