"""add gest_prix table

Revision ID: cf00370dd16d
Revises: 
Create Date: 2025-09-09 08:51:02.684858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf00370dd16d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gest_prix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produit_name', sa.String(length=255), nullable=False),
    sa.Column('duree', sa.String(length=50), nullable=False),
    sa.Column('prix_achat', sa.Float(), nullable=False),
    sa.Column('prix_vente', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gest_prix')
    # ### end Alembic commands ###
