"""add details to commandes_produit, make duree nullable

Revision ID: eafebe726415
Revises: e903f5d5b958
Create Date: 2025-09-11 10:48:29.956616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eafebe726415'
down_revision = 'e903f5d5b958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes_produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.alter_column('duree',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_commandes_produit_produit_id'), ['produit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commandes_produit_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes_produit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commandes_produit_user_id'))
        batch_op.drop_index(batch_op.f('ix_commandes_produit_produit_id'))
        batch_op.alter_column('duree',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('details')

    # ### end Alembic commands ###
